#!/bin/bash

set -e
set -u
set -o pipefail

#   A simple script to hold the varialbes for the NGS Admixture
#   Are you using the Common_Config file?
#       If so, where is it?
COMMON=${HOME}/Deleterious_mutation_project/wild_species_ID/group_bam/Configuration_Files/Common_Config

##############################################################################################
#   If we aren't using the Common_Config file, specify these variables
#   If Common_Config is specified, leave these blank
#   Name the project
PROJECT=

#   Where do we put the outfiles?
    #   Note, the final outdirectory will be
    #   ${SCRATCH}/${PROJECT}/Admixture
SCRATCH=
##############################################################################################

#   The Likelihood file
#       This is the .beagle.gz file from the Site Frequency Spectrum
LIKELIHOOD=${HOME}/scratch/Barley/SFS/Barley_SFSOut.beagle.gz

#   ngsAdmix Parameters
#       Listed below are the defaults, please modify for your samples
K=2
N_CORES=16
MIN_MAF=0.05
